datana:
  jms:
    broker-url: tcp://172.29.40.42:61616
camel:
  component:
    kafka:
      brokers: 172.29.40.42:9092
  springboot:
    main-run-controller: true
    jmx-enabled: false
spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'

debug: true
logging:
  level:
    org:
      camel: INFO
      springframework: INFO
    ru: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'




